Copy gitignore files.
uetchy/create-create-app pull request #39
Opened 2022-06-08 19:27 UTC by iVilja

2022-06-08 22:41 UTC, uetchy requested changes

2022-06-08 22:41 UTC, uetchy commented on src/template.ts
> +    ).replace(/\/gitignore$/, '/.gitignore'); // https://github.com/uetchy/create-create-app/issues/38
For Windows, wrap targetPath in `slash` before replacing path

2022-06-08 23:18 UTC, uetchy commented
Also rebase to the latest commit to ensure GitHub Actions will run the tests for Windows

2022-06-09 02:26 UTC, iVilja commented
Thanks. Done.

2022-06-09 02:34 UTC, merged

2022-06-09 02:35 UTC, uetchy commented
Thanks! @all-contributors add @iVilja for code